### ISSUE TITLE
Issue closed with no further response

### ISSUE THREAD

**Issue by Francesco-FL** [googleads/googleads-mobile-flutter#1080]
Hi, days ago I opened an issue, I was given a "solution" that I don't think is consistent with the open issue (or that I didn't understand). I responded with more information but the issue remained closed and I received no further response.

https://github.com/googleads/googleads-mobile-flutter/issues/1068

**Comment by peterweb2005** [comment]
it happens, 
same for this #906

**Comment by malandr2** [comment]
Hi @Francesco-FL, addressed your issue in the closed out thread.

**Comment by malandr2** [comment]
> it happens, same for this #906
> 
> ## UPDATE
> latest situation: error rating updated from 5.8% to 9.5%

Myself and the flutter engineering have exhausted all options to troubleshoot and this has been marked as infeasible without new information. If you like you can start a thread in the [AdMob Developers forum](https://groups.google.com/g/google-admob-ads-sdk) since it appears to only be affecting Android.

**Comment by peterweb2005** [comment]
@malandr2 

not working
https://groups.google.com/d/msgid/google-admob-ads-sdk/fbeaf3bf-4847-40c7-a801-e41fd464b595n%40googlegroups.com?utm_medium=email&utm_source=footer

**Comment by malandr2** [comment]
Hi @peterweb2005, thanks I've followed up with our team on the Developers to continue triaging your case. There was a second poster who hijacked your original case. Please continue on this thread
