### ISSUE TITLE
migration guide to 5.1

### ISSUE THREAD

**Issue by peterweb2005** [googleads/googleads-mobile-flutter#1106]
as title
seems many updates

thanks

**Comment by malandr2** [comment]
Hi @peterweb2005 you can follow our [Flutter Privacy guide](https://developers.google.com/admob/flutter/privacy) to implement the latest UMP SDK APIs as a part of 5.1.0. 

There is no "migration" guide per se because the APIs from previous versions have not been deprecated and you can still use them.
