### ISSUE TITLE
“GoogleMobileAds.xcframework” is not signed with the expected identity and may have been compromised

### ISSUE THREAD

**Issue by carpentierchloe** [googleads/googleads-mobile-flutter#1186]
Since I have updated everything : android, flutter, brew, pod... I have this issue now when running on IOS. It is well working on Android. I have cleaned and relaunched everything.

google_mobile_ads: ^5.2.0
implementation 'com.google.android.gms:play-services-ads:23.4.0'

**Comment by malandr2** [comment]
Hi @carpentierchloe, since flutter plugin version `5.2.0` uses iOS Google Mobile Ads SDK version `11.10.0` which updated the signing identifity in 11.4.0

Per the [iOS release notes](https://developers.google.com/admob/ios/rel-notes): Updated the signing identity from AdMob Inc. to Google LLC using team ID EQHXZ8M8AV. If this triggers a notice in Xcode, select “Accept Change” to accept the new identity.
