### ISSUE TITLE
Can't import com.google.android.gms.ads.formats.UnifiedNativeAdView;

### ISSUE THREAD

**Issue by arunchaudharyweb** [googleads/googleads-mobile-flutter#218]
When I hover over com.google.android.gms.ads.formats.UnifiedNativeAdView;
I get this error :

Cannot resolve symbol 'UnifiedNativeAdView'

**Comment by Xarastoph** [comment]
I encountered a similar issue and found that the implementation of com.google.android.gms:play-services-ads in my build.gradle was causing the problem. Try commenting it out and see what happens.

**Comment by jjliu15** [comment]
Version 0.12 of the plugin is only compatible with `com.google.android.gms:play-services-ads` up to version 19.7.0, since  `UnifiedNativeAdView` was deleted in version 20.0.0 and renamed to `com.google.android.gms.ads.nativead.NativeAdView`.

Version 0.13.0 of the plugin was just pushed, and is compatible with the latest version of GMASDK.

**Comment by arunchaudharyweb** [comment]
Thanks for the update.
