### ISSUE TITLE
My Test Device Test Ads stopped working after switching to version 0.13

### ISSUE THREAD

**Issue by TheMettaCode** [googleads/googleads-mobile-flutter#253]
After updating to version 0.13, my test device (previously setup through the admob/settings site) stopped showing test ads. is there something particular that I need to update for them to work again?

I went through the admob/settings again and re-added my test device (after deleting the original) and no luck. Is there something programmatically that needs to be changed? 

Thanks for any help

-Metta

**Comment by EngFoggy** [comment]
I have the same issue.
I tried switching back to 0.12.1 and they work like a sharm, but as soon as I switch to 0.13.0 or 0.13.1 i got an "Ad failed to load : 0" message. Clearly, same App ID and Unit ID

**Comment by maheshmnj** [comment]
Hi @TheMettaCode  @EngFoggy , could you guys try with the latest `google_mobile_Ads 0.13.4` and see if that works, If you still face the issue, Please share a [minimal and complete reproducible code](https://stackoverflow.com/help/minimal-reproducible-example)  along with the output of `flutter doctor -v`. 

Note that

0.13.0 has a breaking changes 
```
Removes Ad.isLoaded(). Instead you should use the onAdLoaded callback to track whether an ad is loaded.
Removes need to call Ad.dispose() for Rewarded and Interstitial ads when they fail to load.
```
 please take a look at [this sample code.](https://pub.dev/packages/google_mobile_ads/example)

**Comment by EngFoggy** [comment]
It is difficult for me to provide a minimal sample code, since the sample app works! But when I copy/paste the same functions from the sample app into the app I'm working on...they won't show up. (on a real device they work, and also in production ads are served).
By the way i now switched on 0.13.4 and they still won't show up on emulator (in my app). Nothing that bothers me too much, apart from the bug of the plugin with TabBarViews and GridViews discovered only after release..! XD
