### ISSUE TITLE
Detect AdBlocker

### ISSUE THREAD

**Issue by adriancsbna** [googleads/googleads-mobile-flutter#257]
Hello everyone.

I have detected in my App users that when viewing ads are not displayed giving the error code 2, Network Connection. The strange thing is that my App is made to work only with connection.
I have read that they may have some kind of ad blocker.

Do you know of any way to detect the presence of ad blockers in Flutter?
Does the plugin itself have some kind of functionality to detect it?

**Comment by maheshmnj** [comment]
Hi @adriancsbna, The plugin does not have such feature, Please try asking such questions on community forums like StackOverflow to get some help. Closing since this issue does not seem to report a bug or make a feature request. 
If you disagree feel free to write in the comments and I will reopen it.

Thank you.
