### ISSUE TITLE
Feature Request: Provide Flutter Ads that do not utilize platform views

### ISSUE THREAD

**Issue by Tetracyl** [googleads/googleads-mobile-flutter#440]
I am opening this issue to express my frustration with the google ads mobile flutter package and the challenge of trying to monetize a Flutter app. Ever since this package came out it has been very buggy and there have been tons of issues especially on iOS. 

Over the past year I have spent hours upon hours trying many different ad packages and every single one of them has at least one issue on Android and iOS making it unusable for my app. When I heard about this package when it was released, I was excited to try it out since I knew that the official ad package made by Google had to work. My disappointment was immeasurable though.

Immediately I had noticed that there were many issues with the package, arguably more than some of the unofficial packages, and the implementation of the package was really awkward and did not fit with Flutter's "build once, run anywhere" motto. The issues were very slowly getting resolved and I had to find another package. 

It doesn't make sense for a Flutter ad package made by Google to require you to learn Swift, Android, and XML in order to implement native ads. The Flutter ads package implementation of using platform views to display ads is a very cheap implementation and leads to tons of issues with performance and bugs evident by the amount of issues people have had on this repository. For a whole year now I have been struggling to monetize my app thanks to these issues.

**My proposal:**
This package should provide pure Flutter widgets for all ads out of the box instead of just using platform views and rendering them using native code. The reason so many Flutter developers choose Flutter is because they do not need to build two different apps and many of them (including me) do not know Java or Swift, so it does not make sense for 3/4 of the native ads implementation to require me to code in Swift and Java.

**Comment by liondev7** [comment]
I 100% agree, this package really still needs many improvements in order to live-up to Flutter's own standards and expectations, unfortunately, since we upgraded to this package, our admob account is getting "limited" every week or so because of " invalid traffic ", while traffic is 100% organic & all best practices implemented to the smallest details, the previous package worked much better even with less features, but it was ok, native-ads implementation is a hard without kotlin/swift/xml knowledge and fiddling around... please guys, give some love to this package, i think it makes absolutely no sense for any developer to work on creating Flutter apps without having a robust, simple and working monetization package at hand.

That being said, we highly appreciate all the work being done here & hope everything improves for the better.

**Comment by maheshmnj** [comment]
Hi @Tetracyl, Thanks for filing the issue. This is not the experience we would like to give you. The plugin is being improved everyday. This does look like a valid request to me but I see there is already a similar issue describing this case https://github.com/googleads/googleads-mobile-flutter/issues/313, I would advise you to please follow up there for further updates, Closing this issue as a duplicate. If you disagree feel free to write in the comments and I will reopen it.

Thank you.

**Comment by Tetracyl** [comment]
The other issue seems to be inactive and there hasn't been any updates on it for 4 months now.
