### ISSUE TITLE
When will Interstitial Reward Ad be implemented

### ISSUE THREAD

**Issue by uchidacode** [googleads/googleads-mobile-flutter#497]
It seems to be implemented natively in beta, but when will it arrive in Flutter?

I'm looking forward to seeing it implemented, as I think it's a very effective way for users who don't opt-in to reward ads.

Thanks.

**Comment by maheshmnj** [comment]
Hi @uchidacode, Thanks for filing the issue. I believe you are referring to Rewarded interstitial ads if so this issue is being tracked here https://github.com/googleads/googleads-mobile-flutter/issues/190. Please follow up there for further updates, Closing this issue as a duplicate. If you disagree feel free to write in the comments and I will reopen it.

Thank you.
