### ISSUE TITLE
iOS app rejected Safety Kids - missing parental Gate

### ISSUE THREAD

**Issue by danielefolatelli** [googleads/googleads-mobile-flutter#548]
Hi, mi app can be used for kids so I get it rejected because it does not have a parental gate.
The rejection states that I should add a parental gate before the user can leave the app and ensure that the parental gate cannot be disabled.
Is this a feature that an be integrated into the plugin?
Thanks. Daniele

**Comment by maheshmnj** [comment]
Hi @danielefolatelli, Thanks for filing the issue. The ads plugin currently doesn't support such a feature. I am quite not sure if this is possible to implement because tapping on ads will take you directly to the web. AFAIK the parental gate requires you to show up a puzzle before you visit the web. 

cc: @jjliu15

**Comment by parveenBanuS** [comment]
Facing the same issue. if any possible to add a parental gate before leaving the app? I added when app is launch but it was not accepting again rejected so any possible to added the parental gate in before redirect?
