### ISSUE TITLE
Displaying a Banner Ad statically

### ISSUE THREAD

**Issue by ralfizzle** [googleads/googleads-mobile-flutter#60]
The documentation suggests that Banner Ads can be displayed using a widget, but I see no reference to displaying a Banner Ad statically. Looking at the actual implementation code this is mentioned in a comment, yet there does not seem to be a correlating `show` method for this. Is there a correct way to show a Banner Ad in a static view?

```
/// A banner ad.
///
/// This ad can either be overlaid on top of all flutter widgets as a static
/// view or displayed as a typical Flutter widget. To display as a widget,
/// instantiate an [AdWidget] with this as a parameter.
class BannerAd extends AdWithView {
```

**Comment by ralfizzle** [comment]
In my case I was able to statically show a Banner ad by wrapping my MaterialApp in a Stack as such:
```dart
runApp(
  child: Directionality(
      textDirection: TextDirection.ltr,
      child: Stack(children: [
        MaterialApp(home: MyApp()),
        Container(
          padding: EdgeInsets.only(bottom: 10.0),
          alignment: Alignment.bottomCenter,
          child: BannerAdWidget(AdSize.banner),
        )
      ])));
```

**Comment by danieeelfc** [comment]
@ralfizzle Your code works great. However if I wrap the Stack with a SafeArea widget I get this error: 

`No MediaQuery ancestor could be found starting from the context that was passed to MediaQuery.of(). This can happen because you have not added a WidgetsApp, CupertinoApp, or MaterialApp widget (those widgets introduce a MediaQuery), or it can happen if the context you use comes from a widget above those widgets.`

Isn't it important to use SafeArea in order to avoid some system's nav bar (such as iphone 12 pro max) overlaying the banner?

**Comment by ralfizzle** [comment]
Thank you!

I haven't updated my code since my last comment, but my `MaterialApp` widget build command is wrapped in a SafeArea as such:
```
  @override
  Widget build(BuildContext context) {
    return SafeArea(
```
I don't think it is necessary to wrap the stack in a SafeArea as we only care about the top of the screen for dealing with the notch. Therefore, wrapping the MaterialApp in a SafeArea should be enough and the widgets should fill the space accordingly. I am just guessing though as I have not tested on the iPhone 12 pro max.
