### ISSUE TITLE
Personalized ads not working

### ISSUE THREAD

**Issue by saddem123** [googleads/googleads-mobile-flutter#601]
## Plugin Version
1.3.0

## Steps to Reproduce

1. Create a new app.
2. add `google_mobile_ads`
3. follow this codelab https://codelabs.developers.google.com/codelabs/admob-inline-ads-in-flutter#0 with your ad mob app and ad unit

Expected results: 
**Personalized ads**
Actual results: 
**non personalized ads**

Also, I updated the `request` param 
```
        request: AdManagerAdRequest(
            nonPersonalizedAds: false,
            extras: {'rdp': '1'}
        ),
```

```
        request: AdManagerAdRequest(
            nonPersonalizedAds: false
        ),
```
```
        request: AdManagerAdRequest(
            nonPersonalizedAds: true,
        ),
```
I'm located in Africa so I think there's no need to take into consideration **Consent from European Users** & **[California Consumer Privacy Act (CCPA)](https://support.google.com/admob/answer/9561022)**

**Comment by maheshmnj** [comment]
Hi @saddem123, Thanks for filing the issue. Can you please check these two links perhaps this should help answer your question
https://support.google.com/admob/answer/7676680?hl=en
https://support.google.com/admob/answer/7666519

**Comment by saddem123** [comment]
@maheshmnj  All those rules are for the EU & the UK. And we are located in Africa.
In the official documentation of AdMob they say "**The default behavior of the Google Mobile Ads SDK is to serve personalized ads. If a user has consented to receive only non-personalized ads**" but I get nonPersonalized ads. I don't feel that I'm concerned by the served ads.

**Comment by maheshmnj** [comment]
Thanks for the info @saddem123, Labeling the issue for further investigation from the team
cc: @jjliu15

**Comment by jjliu15** [comment]
Hi @saddem123, how are you determining that the ads are not personalized?

**Comment by saddem123** [comment]
@jjliu15 Ads are the some with `nonPersonalizedAds: true` or `nonPersonalizedAds: false`

**Comment by timothyhoang-google** [comment]
@saddem123 - Can you check whether "npa=1" is present in the ad request when non-personalized ads should be requested? Similarly, ad requests with "npa=0" or missing the parameter will default to personalized ads.

**Comment by saddem123** [comment]
@timothyhoang-google - I added the "npa=1" inside the extras of the AdManagerAdRequest 
test 1:
`
AdManagerAdRequest(
            nonPersonalizedAds: true,
            extras: {'rdp': '1','npa': '1'}
        ),
`

test 2: 
`
request: AdManagerAdRequest(
            nonPersonalizedAds: false,
            extras: {'rdp': '1','npa': '0'}
        ),
`

there no difference between both configuration en term of results.

**Comment by timothyhoang-google** [comment]
@saddem123 - Ads personalization state will be determined by the parameters passed in the ad request. The GMA SDK will look at (1) RDP, (2) NPA, and (3) the consent indicated by the TC string and apply the most conservative setting.

> AdManagerAdRequest( nonPersonalizedAds: true, extras: {'rdp': '1','npa': '1'} )

Ads will not be personalized because npa = 1, rdp = 1.

> request: AdManagerAdRequest( nonPersonalizedAds: false, extras: {'rdp': '1','npa': '0'} )

Ads will not be personalized because rdp = 1.

The scenario you're describing is the SDK working as intended. See (https://developers.google.com/ad-manager/mobile-ads-sdk/android/ccpa) for more info on RDP.

Feel free to re-open this issue if you think there's still a problem.

**Comment by saddem123** [comment]
@timothyhoang-google it's work now thank you.

It should be mentioned in the official documentation that they should pass `extras: {'npa': '0'}` to the ad request to be personalized because when I only use the  `nonPersonalizedAds: false` It didn't work.

In the official documentation  they say "**If non-personalized ads are requested, the ad request URL currently includes &npa=1. However, note that this is an internal implementation detail of the Google Mobile Ads SDK and is subject to change.**" so the developer can't predict that he should add `extras: {'npa': '0'}`

**Comment by timothyhoang-google** [comment]
> It should be mentioned in the official documentation that they should pass extras: {'npa': '0'} to the ad request to be personalized because when I only use the nonPersonalizedAds: false It didn't work.

Are you getting cases where you're seeing `npa=1` in the ad request when you're setting `nonPersonalizedAds: false` or vice versa?

From our [developer documentation](https://developers.google.com/admob/flutter/eu-consent#forward_consent_to_the_google_mobile_ads_sdk), the following should be sufficient to forward the user's consent state to the GMA SDK:
`AdRequest(nonPersonalizedAds: true)`

For reference, here are sample requests and the expected personalization behavior:
1. AdManagerAdRequest( nonPersonalizedAds: true, extras: {'rdp': '1'} ) --> non-personalized ads
2. AdManagerAdRequest( nonPersonalizedAds: false, extras: {'rdp': '1'} ) --> non-personalized ads
3. AdManagerAdRequest( nonPersonalizedAds: true, extras: {'rdp': '0'} ) --> non-personalized ads
4. AdManagerAdRequest( nonPersonalizedAds: false, extras: {'rdp': '0'} ) --> personalized ads

In all of the cases above, setting the npa bit is not needed since it should match the nonPersonalizedAds boolean. If there is for example a developer mistake and npa bit doesn't match the nonPersonalizedAds boolean, then ads will be non personalized because this is the most conservative state (e.g. is_non_personalized = nonPersonalizedAds OR npa OR rdp) .

If we were to expand the examples above, the npa bit wouldn't impact the personalization state of #1-3: All ads in these cases will be non-personalized. For #4:
4a. AdManagerAdRequest( nonPersonalizedAds: false, extras: {'rdp': '0', 'npa': '0'} ) --> personalized ads
4b. AdManagerAdRequest( nonPersonalizedAds: false, extras: {'rdp': '0', 'npa': '1'} ) --> non-personalized ads

**Comment by saddem123** [comment]
@timothyhoang-google what I didn't understand was how to check if the add request if it sends npa=1 or npa=0  ?

**Comment by timothyhoang-google** [comment]
You can check the ad request by collecting a Network Trace ([android](https://developers.google.com/admob/android/network-tracing), [ios](https://developers.google.com/admob/ios/network-tracing)) or setting up a proxy (e.g. [Charles](https://www.charlesproxy.com/)).

You'll be able to identify ad requests by filtering for 'doubleclick.net/gampad'. Check the [query string](https://en.wikipedia.org/wiki/Query_string) for 'npa=1'
