### ISSUE TITLE
Native Ads Show Issue

### ISSUE THREAD

**Issue by VPATEL007** [googleads/googleads-mobile-flutter#623]
**Actual results:** 

<details>
  <summary>Logs</summary>

```
```

```
```

```
```

</details>

**Comment by huycozy** [comment]
Hi @VPATEL007 
When opening an issue, please try to provide all or some of the information indicated in the [template](https://github.com/googleads/googleads-mobile-flutter/issues/new?assignees=&labels=&template=2_bug.md&title=) so that we can address this issue properly.

<details>
<summary>Issue Template</summary>



## Plugin Version



## Steps to Reproduce



1. Run `flutter create bug`.
2. Update the files as follows: ... 
3. ... 

**Expected results:** 

**Actual results:** 

<details>
  <summary>Logs</summary>



```
```



```
```



```
```

</details>

</details>

Closing. Once you update the issue, please write in the comments and I will reopen it.
Thank you!
