### ISSUE TITLE
Minimum API Level 16 support? 

### ISSUE THREAD

**Issue by ilkercankaya** [googleads/googleads-mobile-flutter#63]
Hi Everyone, 

On the documentation it says that the minimum required API level is 19. ~ 2% 3% android OS are below API level 19. I was using firebase admob and my apps minumum API was 16. I kindly don't want to update my minimum api to 19 and lose all the hard work I've done to keep the level on 16 just for one package even though it is the package that generates me the revenue. 

Minimum API level of 16 support would be awesome.

**Comment by bdlukaa** [comment]
The reason it requires API level 19 is because it uses [platform views](https://flutter.dev/docs/development/platform-integration/platform-views?tab=android-platform-views-kotlin-tab#on-the-platform-side). There should be a way to use Interstitial and Rewarded ads in API level 16.

You can use [my package](https://pub.dev/packages/native_admob_flutter). It doesn't require API Level 19 for Full Screen Ads (Rewarded, Interstitial, App Open and Rewarded Interstitial Ads)

**Comment by ilkercankaya** [comment]
if that is the case then, can we not just override the package with `<uses-sdk tools:overrideLibrary="THIS_LIBS_PACKAGE_NAME"/>` in manifest file and use it?

**Comment by bdlukaa** [comment]
Yeah, we can. But remember that Native and Banner Ads require API 19

**Comment by maheshmnj** [comment]
labelling as a valid feature request

**Comment by jjliu15** [comment]
We don't plan on officially supporting API 16 due to platform view limitations. As mentioned in https://github.com/googleads/googleads-mobile-flutter/issues/63#issuecomment-800317864 you can still override it manually in your app. Also please note that the next major android release ([21.0.0](https://developers.google.com/admob/android/rel-notes)) will only support 19 and higher.
