### ISSUE TITLE
LoadAdError(Code: 3, domain: com.google.adnroid.gms.ads, message: Account not approved yet ...

### ISSUE THREAD

**Issue by llwasampijja** [googleads/googleads-mobile-flutter#630]
The test ads work fine, the account is approved, and the ads app approval status is ready. There are also no policy violations. The only issue which I think could be causing this error is 
Your ad serving is disabled
"``` Your ad units are not serving ads in your app(s) and you’re not being paid. This is because you haven't verified your payment address. Please contact support to verify your payment address.```" message on the dashboard. Could this be the cause? If so, I think the error returned by the package is misleading, because when you go to the link in the error message, it takes to a help page where they are troubleshooting a different scenario from the one am facing. I think it would be more helpful if this scenario returns an error message fitting the cause.

Any suggestions on some of the other issues that could possibly be causing this error would be very much appreciated.
I apologize if I have posted this on the wrong forum.

Thanks in advance

**Comment by huycozy** [comment]
Hi @llwasampijja, thanks for filing the issue. 
From the message on the dashboard, I think it could be the cause of the issue. Please check this article that may help you solve the issue: https://support.google.com/admob/answer/3198657?hl=en

Also, could you please provide full of the error message that contains the link?
>because when you go to the link in the error message, it takes to a help page where they are troubleshooting a different scenario from the one am facing.

**Comment by umitmutluu** [comment]
I have the same problem, sometimes I can watch videos 3 times on the device, but sometimes even 1 of them gives this error when opening, I throw the error exactly->

` InterstitialAd failed to load: LoadAdError(code: 0, domain: com.google.android.gms.ads, message: Internal error., responseInfo: ResponseInfo(responseId: w2wDY76ZKfrH7_UP7YWAkAY, mediationAdapterClassName: , adapterResponses: [AdapterResponseInfo(adapterClassName: com.google.ads.mediation.admob.AdMobAdapter, latencyMillis: 60031), description: {
I/flutter (30165):   "Adapter": "com.google.ads.mediation.admob.AdMobAdapter",
I/flutter (30165):   "Latency": 60031,
I/flutter (30165):   "Credentials": {
I/flutter (30165):     "pubid": "ca-app-pub-3940256099942544\/5224354917\/cak=no_cache&cadc=7d&caqid=w2wDY72CKNWw9u8P-uC1uAQ",
I/flutter (30165):     "campaign_id": "1057492276"
I/flutter (30165):   },
I/flutter (30165):   "Ad Error": {
I/flutter (30165):     "Code": 0,
I/flutter (30165):     "Message": "Internal error.",
I/flutter (30165):     "Domain": "com.google.android.gms.ads",
I/flutter (30165):     "Cause": "null"
I/flutter (30165):   }
I/flutter (30165): }, adUnitMapping: {pubid: ca-app-pub-3940256099942544/5224354917/cak=no_cache&cadc=7d&caqid=w2wDY72CKNWw9u8P-uC1uAQ, campaign_id: 1057492276}, adError: AdError(code: 0, domain: com.google.android.gms.ads, message: Internal error.))])).
I/DynamiteModule(30165): Considering local module com.google.android.gms.ads.dynamite:0 and remote module com.google.android.gms.ads.dynamite:221908400
I/DynamiteModule(30165): Selected remote version of com.google.android.gms.ads.dynamite, version >= 221908400
V/DynamiteModule(30165): Dynamite loader version >= 2, using loadModule2NoCrashUtils
I/Ads     (30165): Use RequestConfiguration.Builder().setTestDeviceIds(Arrays.asList("53BA3CB669E5C41276ED3B0978812BA3")) to get test ads on this device.
W/ConnectionStatusConfig(30165): Dynamic lookup for intent failed for action: com.google.android.gms.ads.service.CACHE
V/AudioManager(30165): getRingerMode...
W/ConnectionStatusConfig(30165): Dynamic lookup for intent failed for action: com.google.android.gms.ads.service.START
W/Ads     (30165): Failed to preload url https://rr2---sn-8vq54voxu-5qce.googlevideo.com/videoplayback?expire=1661197635&ei=w2wDY6i7Noik8gP_7qToCQ&ip=149.140.73.150&id=f9ead5933fc112a7&itag=22&source=youtube&requiressl=yes&mh=EA&mm=31&mn=sn-8vq54voxu-5qce&ms=au&mv=m&mvi=2&pcm2cms=yes&pl=22&susc=gvp&acao=yes&ctier=L&mime=video%2Fmp4&vprv=1&dur=7.267&lmt=1609247274254961&mt=1661168495&txp=1211222&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Csusc%2Cacao%2Cctier%2Cmime%2Cvprv%2Cdur%2Clmt&sig=AOq0QJ8wRQIhAMngnpLVx-hN6nCOr8yQ11E8idJ0n_2P8qjW3zbqfqh_AiAaaH9g60aI_zFnONxgh4KaAjbXO1GA692xi_4zXf426w%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpcm2cms%2Cpl&lsig=AG3C_xAwRQIgW_uY9TGEZCQ-Cg2WrNP6vGMExKTHoV-iPuWSMmJV2V8CIQCDHVaD2XOlbw0Ox2WeOlNI119IFOIkafWcE20-7aa0yg%3D%3D&cpn=S8dRieC3suqy9uds&ic=gmasdk Exception: ExoPlayer was released during preloading.
W/Ads     (30165): #004 The webview is destroyed. Ignoring action.
[log] <<< h
I/Ads     (30165): Ad failed to load : 2
I/flutter (30165): InterstitialAd failed to load: LoadAdError(code: 2, domain: com.google.android.gms.ads, message: Network error., responseInfo: ResponseInfo(responseId: null, mediationAdapterClassName: , adapterResponses: [])).
I/DynamiteModule(30165): Considering local module com.google.android.gms.ads.dynamite:0 and remote module com.google.android.gms.ads.dynamite:221908400
I/DynamiteModule(30165): Selected remote version of com.google.android.gms.ads.dynamite, version >= 221908400
V/DynamiteModule(30165): Dynamite loader version >= 2, using loadModule2NoCrashUtils
I/Ads     (30165): Use RequestConfiguration.Builder().setTestDeviceIds(Arrays.asList("53BA3CB669E5C41276ED3B0978812BA3")) to get test ads on this device.
V/AudioManager(30165): getRingerMode...
W/ConnectionStatusConfig(30165): Dynamic lookup for intent failed for action: com.google.android.gms.ads.service.START
[log] <<< h
I/ExoPlayerImpl(30165): Init ExoPlayerLib/2.4.2 [HWLDN-Q, LDN-L01, HUAWEI, 26]
D/MetadataUtil(30165): Skipped unknown metadata entry: gsst
D/MetadataUtil(30165): Skipped unknown metadata entry: gstd
I/OMXClient(30165): Treble IOmx obtained
I/ACodec  (30165): In onAllocateComponent create compenent, codec name: OMX.google.aac.decoder
W/HwExtendedUtils(30165): hw configLocalPlayBack err = -2147483648
I/ACodec  (30165): onStart
I/OMXClient(30165): Treble IOmx obtained
W/ACodec  (30165): Allocating component 'OMX.qcom.video.decoder.avc' failed, try next one.
E/ACodec  (30165): Unable to instantiate codec 'OMX.qcom.video.decoder.avc' with err 0xfffffff4.
E/ACodec  (30165): signalError(omxError 0xfffffff4, internalError -12)
E/MediaCodec(30165): Codec reported err 0xfffffff4, actionCode 0, while in state 1
W/MediaCodec-JNI(30165): try to release MediaCodec from JMediaCodec::~JMediaCodec()...
W/MediaCodec-JNI(30165): done releasing MediaCodec from JMediaCodec::~JMediaCodec().
E/ExoPlayerImplInternal(30165): Renderer error.
E/ExoPlayerImplInternal(30165): com.google.android.gms.ads.exoplayer3.c
E/ExoPlayerImplInternal(30165): 	at com.google.android.gms.ads.exoplayer3.mediacodec.c.N(:com.google.android.gms.policy_ads_fdr_dynamite@221908400@221908400000.447330857.447330857:16)
E/ExoPlayerImplInternal(30165): 	at com.google.android.gms.ads.exoplayer3.mediacodec.c.G(:com.google.android.gms.policy_ads_fdr_dynamite@221908400@221908400000.447330857.447330857:4)
E/ExoPlayerImplInternal(30165): 	at com.google.android.gms.ads.exoplayer3.video.h.G(:com.google.android.gms.policy_ads_fdr_dynamite@221908400@221908400000.447330857.447330857:1)
E/ExoPlayerImplInternal(30165): 	at com.google.android.gms.ads.exoplayer3.mediacodec.c.z(:com.google.android.gms.policy_ads_fdr_dynamite@221908400@221908400000.447330857.447330857:3)
E/ExoPlayerImplInternal(30165): 	at com.google.android.gms.ads.exoplayer3.n.handleMessage(:com.google.android.gms.policy_ads_fdr_dynamite@221908400@221908400000.447330857.447330857:41)
E/ExoPlayerImplInternal(30165): 	at android.os.Handler.dispatchMessage(Handler.java:104)
E/ExoPlayerImplInternal(30165): 	at android.os.Looper.loop(Looper.java:166)
E/ExoPlayerImplInternal(30165): 	at android.os.HandlerThread.run(HandlerThread.java:65)
E/ExoPlayerImplInternal(30165): Caused by: com.google.android.gms.ads.exoplayer3.mediacodec.b: Decoder init failed: OMX.qcom.video.decoder.avc, Format(1, null, video/avc, -1, null, [1280, 720, -1.0], [-1, -1])
E/ExoPlayerImplInternal(30165): 	at com.google.android.gms.ads.exoplayer3.mediacodec.c.N(:com.google.android.gms.policy_ads_fdr_dynamite@221908400@221908400000.447330857.447330857:15)
E/ExoPlayerImplInternal(30165): 	... 7 more
E/ExoPlayerImplInternal(30165): Caused by: android.media.MediaCodec$CodecException: Failed to initialize OMX.qcom.video.decoder.avc, error 0xfffffff4
E/ExoPlayerImplInternal(30165): 	at android.media.MediaCodec.native_setup(Native Method)
E/ExoPlayerImplInternal(30165): 	at android.media.MediaCodec.<init>(MediaCodec.java:1793)
E/ExoPlayerImplInternal(30165): 	at android.media.MediaCodec.createByCodecName(MediaCodec.java:1774)
E/ExoPlayerImplInternal(30165): 	at com.google.android.gms.ads.exoplayer3.mediacodec.c.N(:com.google.android.gms.policy_ads_fdr_dynamite@221908400@221908400000.447330857.447330857:13)
E/ExoPlayerImplInternal(30165): 	... 7 more
W/ACodec  (30165): forcing OMX state to Idle when received shutdown in ExecutingState
W/Ads     (30165): Precache error
W/Ads     (30165): com.google.android.gms.ads.exoplayer3.c
W/Ads     (30165): 	at com.google.android.gms.ads.exoplayer3.mediacodec.c.N(:com.google.android.gms.policy_ads_fdr_dynamite@221908400@221908400000.447330857.447330857:16)
W/Ads     (30165): 	at com.google.android.gms.ads.exoplayer3.mediacodec.c.G(:com.google.android.gms.policy_ads_fdr_dynamite@221908400@221908400000.447330857.447330857:4)
W/Ads     (30165): 	at com.google.android.gms.ads.exoplayer3.video.h.G(:com.google.android.gms.policy_ads_fdr_dynamite@221908400@221908400000.447330857.447330857:1)
W/Ads     (30165): 	at com.google.android.gms.ads.exoplayer3.mediacodec.c.z(:com.google.android.gms.policy_ads_fdr_dynamite@221908400@221908400000.447330857.447330857:3)
W/Ads     (30165): 	at com.google.android.gms.ads.exoplayer3.n.handleMessage(:com.google.android.gms.policy_ads_fdr_dynamite@221908400@221908400000.447330857.447330857:41)
W/Ads     (30165): 	at android.os.Handler.dispatchMessage(Handler.java:104)
W/Ads     (30165): 	at android.os.Looper.loop(Looper.java:166)
W/Ads     (30165): 	at android.os.HandlerThread.run(HandlerThread.java:65)
W/Ads     (30165): Caused by: com.google.android.gms.ads.exoplayer3.mediacodec.b: Decoder init failed: OMX.qcom.video.decoder.avc, Format(1, null, video/avc, -1, null, [1280, 720, -1.0], [-1, -1])
W/Ads     (30165): 	at com.google.android.gms.ads.exoplayer3.mediacodec.c.N(:com.google.android.gms.policy_ads_fdr_dynamite@221908400@221908400000.447330857.447330857:15)
W/Ads     (30165): 	... 7 more
W/Ads     (30165): Caused by: android.media.MediaCodec$CodecException: Failed to initialize OMX.qcom.video.decoder.avc, error 0xfffffff4
W/Ads     (30165): 	at android.media.MediaCodec.native_setup(Native Method)
W/Ads     (30165): 	at android.media.MediaCodec.<init>(MediaCodec.java:1793)
W/Ads     (30165): 	at android.media.MediaCodec.createByCodecName(MediaCodec.java:1774)
W/Ads     (30165): 	at com.google.android.gms.ads.exoplayer3.mediacodec.c.N(:com.google.android.gms.policy_ads_fdr_dynamite@221908400@221908400000.447330857.447330857:13)
W/Ads     (30165): 	... 7 more
I/zygote64(30165): Background concurrent copying GC freed 357759(14MB) AllocSpace objects, 31(3MB) LOS objects, 50% free, 18MB/36MB, paused 3.741ms total 165.163ms
[log] <<< h
I/Ads     (30165): Ad failed to load : 2`

**Comment by huycozy** [comment]
Hi @umitmutluu 
>I/flutter (30165): InterstitialAd failed to load: LoadAdError(code: 2, domain: com.google.android.gms.ads, message: Network error., responseInfo: ResponseInfo(responseId: null, mediationAdapterClassName: , adapterResponses: [])).

Please make sure you have an internet connection on the device while doing the test. 

>I/Ads     (30165): Use RequestConfiguration.Builder().setTestDeviceIds(Arrays.asList("53BA3CB669E5C41276ED3B0978812BA3")) to get test ads on this device.

Also, you should add the test device id as the hint from the logs.

**Comment by llwasampijja** [comment]
> Hi @llwasampijja, thanks for filing the issue. From the message on the dashboard, I think it could be the cause of the issue. Please check this article that may help you solve the issue: https://support.google.com/admob/answer/3198657?hl=en
> 
> Also, could you please provide full of the error message that contains the link?
> 
> > because when you go to the link in the error message, it takes to a help page where they are troubleshooting a different scenario from the one am facing.

Hello @huycozy thanks for your response,l and I am going to look at the link that you provided. Below is the complete error message that is returned by the package's "onAdFailedToLoad" callback function.
```
LoadAdError(code: 3, domain: com.google.android.gms.ads, message: Account not approved yet. <https://support.google.com/admob/answer/9905175#1>, responseInfo: ResponseInfo(responseId: null, mediationAdapterClassName: , adapterResponses: []))
```

Thanks

**Comment by huycozy** [comment]
@llwasampijja There is also a checklist that may help you: https://support.google.com/admob/thread/147648534?hl=en&msgid=147679347
Try to solve the issue from the dashboard and retry testing the application to see if the issue is still reproducible.

**Comment by mujahid-dzinemedia** [comment]
PlayConsole Crash details : 
com.google.android.gms.policy_ads_fdr_dynamite@223104600@223104600057.463978484.463978484 - asa.a

`Exception java.lang.OutOfMemoryError: pthread_create (1040KB stack) failed: Try again
  at java.lang.Thread.nativeCreate
  at java.lang.Thread.start (Thread.java:883)
  at com.google.android.gms.ads.exoplayer3.n.<init> (:com.google.android.gms.policy_ads_fdr_dynamite@223104600@223104600057.463978484.463978484:5)
  at com.google.android.gms.ads.exoplayer3.i.<init> (:com.google.android.gms.policy_ads_fdr_dynamite@223104600@223104600057.463978484.463978484:5)
  at com.google.android.gms.ads.internal.video.exoplayer3.ad.<init> (:com.google.android.gms.policy_ads_fdr_dynamite@223104600@223104600057.463978484.463978484:8)
  at com.google.android.gms.ads.internal.video.gmsg.exoplayer3.e.<init> (:com.google.android.gms.policy_ads_fdr_dynamite@223104600@223104600057.463978484.463978484:3)
  at com.google.android.gms.ads.internal.video.gmsg.r.a (:com.google.android.gms.policy_ads_fdr_dynamite@223104600@223104600057.463978484.463978484:24)
  at com.google.android.gms.ads.internal.webview.q.A (:com.google.android.gms.policy_ads_fdr_dynamite@223104600@223104600057.463978484.463978484:4)
  at com.google.android.gms.ads.internal.webview.q.e (:com.google.android.gms.policy_ads_fdr_dynamite@223104600@223104600057.463978484.463978484:8)
  at com.google.android.gms.ads.internal.webview.ah.run (:com.google.android.gms.policy_ads_fdr_dynamite@223104600@223104600057.463978484.463978484:4)
  at android.os.Handler.handleCallback (Handler.java:883)
  at android.os.Handler.dispatchMessage (Handler.java:100)
  at asa.a (:com.google.android.gms.policy_ads_fdr_dynamite@223104600@223104600057.463978484.463978484)
  at com.google.android.gms.ads.internal.util.f.a (:com.google.android.gms.policy_ads_fdr_dynamite@223104600@223104600057.463978484.463978484:1)
  at asa.dispatchMessage (:com.google.android.gms.policy_ads_fdr_dynamite@223104600@223104600057.463978484.463978484)
  at android.os.Looper.loop (Looper.java:223)
  at android.app.ActivityThread.main (ActivityThread.java:7562)
  at java.lang.reflect.Method.invoke
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:539)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:950)`

**Comment by mujahid-dzinemedia** [comment]
:com.google.android.gms.policy_ads_fdr_dynamite@223104600@223104600057.463978484.463978484 - asa.a
java.lang.OutOfMemoryError

**Comment by mujahid-dzinemedia** [comment]
java.lang.OutOfMemoryError 

` implementation 'com.google.android.gms:play-services-ads:21.3.0'`

```
Exception java.lang.OutOfMemoryError: pthread_create (1040KB stack) failed: Try again
  at java.lang.Thread.nativeCreate
  at java.lang.Thread.start (Thread.java:733)
  at java.util.concurrent.ThreadPoolExecutor.addWorker (ThreadPoolExecutor.java:975)
  at java.util.concurrent.ThreadPoolExecutor.execute (ThreadPoolExecutor.java:1382)
  at com.google.android.gms.ads.internal.util.future.d.execute (:com.google.android.gms.policy_ads_fdr_dynamite@223104600@223104600057.463978484.463978484)
  at com.google.android.gms.ads.nonagon.ad.activeview.b.a (:com.google.android.gms.policy_ads_fdr_dynamite@223104600@223104600057.463978484.463978484:3)
  at com.google.android.gms.ads.internal.js.k.a (:com.google.android.gms.policy_ads_fdr_dynamite@223104600@223104600057.463978484.463978484:2)
  at com.google.android.gms.ads.internal.webview.q.A (:com.google.android.gms.policy_ads_fdr_dynamite@223104600@223104600057.463978484.463978484:4)
  at com.google.android.gms.ads.internal.webview.q.e (:com.google.android.gms.policy_ads_fdr_dynamite@223104600@223104600057.463978484.463978484:8)
  at com.google.android.gms.ads.internal.webview.ah.run (:com.google.android.gms.policy_ads_fdr_dynamite@223104600@223104600057.463978484.463978484:4)
  at android.os.Handler.handleCallback (Handler.java:873)
  at android.os.Handler.dispatchMessage (Handler.java:99)
  at asa.a (:com.google.android.gms.policy_ads_fdr_dynamite@223104600@223104600057.463978484.463978484)
  at com.google.android.gms.ads.internal.util.f.a (:com.google.android.gms.policy_ads_fdr_dynamite@223104600@223104600057.463978484.463978484:1)
  at asa.dispatchMessage (:com.google.android.gms.policy_ads_fdr_dynamite@223104600@223104600057.463978484.463978484)
  at android.os.Looper.loop (Looper.java:201)
  at android.app.ActivityThread.main (ActivityThread.java:6861)
  at java.lang.reflect.Method.invoke
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:547)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:873)
```

**Comment by mujahid-dzinemedia** [comment]
java.lang.OutOfMemoryError

`implementation 'com.google.android.gms:play-services-ads:21.3.0'`

`Exception java.lang.OutOfMemoryError: pthread_create (1040KB stack) failed: Try again
  at java.lang.Thread.nativeCreate
  at java.lang.Thread.start (Thread.java:883)
  at java.util.concurrent.ThreadPoolExecutor.addWorker (ThreadPoolExecutor.java:975)
  at java.util.concurrent.ThreadPoolExecutor.execute (ThreadPoolExecutor.java:1382)
  at java.util.concurrent.Executors$DelegatedExecutorService.execute (Executors.java:630)
  at com.google.android.gms.ads.exoplayer3.upstream.n.c (:com.google.android.gms.policy_ads_fdr_dynamite@223104600@223104600057.463978484.463978484)
  at com.google.android.gms.ads.exoplayer3.upstream.n.b (:com.google.android.gms.policy_ads_fdr_dynamite@223104600@223104600057.463978484.463978484:3)
  at com.google.android.gms.ads.exoplayer3.source.i.r (:com.google.android.gms.policy_ads_fdr_dynamite@223104600@223104600057.463978484.463978484:5)
  at com.google.android.gms.ads.exoplayer3.source.i.n (:com.google.android.gms.policy_ads_fdr_dynamite@223104600@223104600057.463978484.463978484)
  at com.google.android.gms.ads.exoplayer3.source.p.n (:com.google.android.gms.policy_ads_fdr_dynamite@223104600@223104600057.463978484.463978484)
  at com.google.android.gms.ads.exoplayer3.n.handleMessage (:com.google.android.gms.policy_ads_fdr_dynamite@223104600@223104600057.463978484.463978484:18)
  at android.os.Handler.dispatchMessage (Handler.java:103)
  at android.os.Looper.loop (Looper.java:225)
  at android.os.HandlerThread.run (HandlerThread.java:67)`

**Comment by mujahid-dzinemedia** [comment]
[FATAL:output_surface_provider_webview.cc(78)] Non owned context lost!
`implementation 'com.google.android.gms:play-services-ads:21.3.0'`

`*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
pid: 0, tid: 0 >>> com.dzinemedia.logomaker <<<

backtrace:
  #00  pc 0x0000000002573fe0  /data/app/com.google.android.trichromelibrary_489608830-HEzf0gJcvqs6OmAzQXV4tw==/base.apk!libmonochrome.so
  #01  pc 0x0000000000d564dd  /data/app/com.google.android.trichromelibrary_489608830-HEzf0gJcvqs6OmAzQXV4tw==/base.apk!libmonochrome.so
  #02  pc 0x00000000030ae8e7  /data/app/com.google.android.trichromelibrary_489608830-HEzf0gJcvqs6OmAzQXV4tw==/base.apk!libmonochrome.so
  #03  pc 0x0000000002c6d3e1  /data/app/com.google.android.trichromelibrary_489608830-HEzf0gJcvqs6OmAzQXV4tw==/base.apk!libmonochrome.so
  #04  pc 0x0000000002c6d339  /data/app/com.google.android.trichromelibrary_489608830-HEzf0gJcvqs6OmAzQXV4tw==/base.apk!libmonochrome.so
  #05  pc 0x0000000002c1aa1f  /data/app/com.google.android.trichromelibrary_489608830-HEzf0gJcvqs6OmAzQXV4tw==/base.apk!libmonochrome.so
  #06  pc 0x0000000002bdd39b  /data/app/com.google.android.trichromelibrary_489608830-HEzf0gJcvqs6OmAzQXV4tw==/base.apk!libmonochrome.so
  #07  pc 0x0000000002bdd34f  /data/app/com.google.android.trichromelibrary_489608830-HEzf0gJcvqs6OmAzQXV4tw==/base.apk!libmonochrome.so
  #08  pc 0x0000000002bdd309  /data/app/com.google.android.trichromelibrary_489608830-HEzf0gJcvqs6OmAzQXV4tw==/base.apk!libmonochrome.so
  #09  pc 0x0000000001bfb04f  /data/app/com.google.android.trichromelibrary_489608830-HEzf0gJcvqs6OmAzQXV4tw==/base.apk!libmonochrome.so
  #10  pc 0x0000000000d5d3cf  /data/app/com.google.android.trichromelibrary_489608830-HEzf0gJcvqs6OmAzQXV4tw==/base.apk!libmonochrome.so
  #11  pc 0x0000000000d5d4a9  /data/app/com.google.android.trichromelibrary_489608830-HEzf0gJcvqs6OmAzQXV4tw==/base.apk!libmonochrome.so
  #12  pc 0x0000000001bfb04f  /data/app/com.google.android.trichromelibrary_489608830-HEzf0gJcvqs6OmAzQXV4tw==/base.apk!libmonochrome.so
  #13  pc 0x0000000000d5d703  /data/app/com.google.android.trichromelibrary_489608830-HEzf0gJcvqs6OmAzQXV4tw==/base.apk!libmonochrome.so
  #14  pc 0x0000000000d5dbab  /data/app/com.google.android.trichromelibrary_489608830-HEzf0gJcvqs6OmAzQXV4tw==/base.apk!libmonochrome.so
  #15  pc 0x0000000000d557db  /data/app/com.google.android.trichromelibrary_489608830-HEzf0gJcvqs6OmAzQXV4tw==/base.apk!libmonochrome.so
  #16  pc 0x0000000000d54a77  /data/app/com.google.android.trichromelibrary_489608830-HEzf0gJcvqs6OmAzQXV4tw==/base.apk!libmonochrome.so
  #17  pc 0x0000000000d5a6ff  /data/app/com.google.android.trichromelibrary_489608830-HEzf0gJcvqs6OmAzQXV4tw==/base.apk!libmonochrome.so
  #18  pc 0x0000000000d4fd29  /data/app/com.google.android.trichromelibrary_489608830-HEzf0gJcvqs6OmAzQXV4tw==/base.apk!libmonochrome.so
  #19  pc 0x0000000000002263  /system/lib/libwebviewchromium_plat_support.so (android::(anonymous namespace)::draw_gl(int, void*, android::uirenderer::DrawGlInfo const&)+198)
  #20  pc 0x0000000000541403  /system/lib/libhwui.so (android::uirenderer::WebViewFunctor::drawGl(android::uirenderer::DrawGlInfo const&)+54)
  #21  pc 0x0000000000273ed9  /system/lib/libhwui.so (android::uirenderer::skiapipeline::GLFunctorDrawable::onDraw(SkCanvas*)+1720)
  #22  pc 0x00000000003e4cef  /system/lib/libhwui.so (SkCanvas::onDrawDrawable(SkDrawable*, SkMatrix const*)+166)
  #23  pc 0x00000000002c00b1  /system/lib/libhwui.so (android::uirenderer::skiapipeline::RenderNodeDrawable::onDraw(SkCanvas*)+756)
  #24  pc 0x00000000003e4cb7  /system/lib/libhwui.so (SkCanvas::onDrawDrawable(SkDrawable*, SkMatrix const*)+110)
  #25  pc 0x00000000002c00b1  /system/lib/libhwui.so (android::uirenderer::skiapipeline::RenderNodeDrawable::onDraw(SkCanvas*)+756)
  #26  pc 0x00000000003e4cb7  /system/lib/libhwui.so (SkCanvas::onDrawDrawable(SkDrawable*, SkMatrix const*)+110)
  #27  pc 0x00000000002c00b1  /system/lib/libhwui.so (android::uirenderer::skiapipeline::RenderNodeDrawable::onDraw(SkCanvas*)+756)
  #28  pc 0x00000000003e4cb7  /system/lib/libhwui.so (SkCanvas::onDrawDrawable(SkDrawable*, SkMatrix const*)+110)
  #29  pc 0x00000000002c00b1  /system/lib/libhwui.so (android::uirenderer::skiapipeline::RenderNodeDrawable::onDraw(SkCanvas*)+756)
  #30  pc 0x00000000003e4cb7  /system/lib/libhwui.so (SkCanvas::onDrawDrawable(SkDrawable*, SkMatrix const*)+110)
  #31  pc 0x00000000002c00b1  /system/lib/libhwui.so (android::uirenderer::skiapipeline::RenderNodeDrawable::onDraw(SkCanvas*)+756)
  #32  pc 0x00000000003e4cb7  /system/lib/libhwui.so (SkCanvas::onDrawDrawable(SkDrawable*, SkMatrix const*)+110)
  #33  pc 0x00000000002c00b1  /system/lib/libhwui.so (android::uirenderer::skiapipeline::RenderNodeDrawable::onDraw(SkCanvas*)+756)
  #34  pc 0x00000000003e4cb7  /system/lib/libhwui.so (SkCanvas::onDrawDrawable(SkDrawable*, SkMatrix const*)+110)
  #35  pc 0x00000000002c00b1  /system/lib/libhwui.so (android::uirenderer::skiapipeline::RenderNodeDrawable::onDraw(SkCanvas*)+756)
  #36  pc 0x00000000003e4cb7  /system/lib/libhwui.so (SkCanvas::onDrawDrawable(SkDrawable*, SkMatrix const*)+110)
  #37  pc 0x00000000002c00b1  /system/lib/libhwui.so (android::uirenderer::skiapipeline::RenderNodeDrawable::onDraw(SkCanvas*)+756)
  #38  pc 0x00000000003e4cb7  /system/lib/libhwui.so (SkCanvas::onDrawDrawable(SkDrawable*, SkMatrix const*)+110)
  #39  pc 0x00000000002c00b1  /system/lib/libhwui.so (android::uirenderer::skiapipeline::RenderNodeDrawable::onDraw(SkCanvas*)+756)
  #40  pc 0x00000000003e4cb7  /system/lib/libhwui.so (SkCanvas::onDrawDrawable(SkDrawable*, SkMatrix const*)+110)
  #41  pc 0x00000000002c00b1  /system/lib/libhwui.so (android::uirenderer::skiapipeline::RenderNodeDrawable::onDraw(SkCanvas*)+756)
  #42  pc 0x00000000003e4cb7  /system/lib/libhwui.so (SkCanvas::onDrawDrawable(SkDrawable*, SkMatrix const*)+110)
  #43  pc 0x00000000002c00b1  /system/lib/libhwui.so (android::uirenderer::skiapipeline::RenderNodeDrawable::onDraw(SkCanvas*)+756)
  #44  pc 0x00000000003e4cb7  /system/lib/libhwui.so (SkCanvas::onDrawDrawable(SkDrawable*, SkMatrix const*)+110)
  #45  pc 0x00000000002c00b1  /system/lib/libhwui.so (android::uirenderer::skiapipeline::RenderNodeDrawable::onDraw(SkCanvas*)+756)
  #46  pc 0x00000000003e4cb7  /system/lib/libhwui.so (SkCanvas::onDrawDrawable(SkDrawable*, SkMatrix const*)+110)
  #47  pc 0x00000000002c00b1  /system/lib/libhwui.so (android::uirenderer::skiapipeline::RenderNodeDrawable::onDraw(SkCanvas*)+756)
  #48  pc 0x00000000002bfd3f  /system/lib/libhwui.so (SkDrawable::draw(SkCanvas*, SkMatrix const*)+46)
  #49  pc 0x00000000002e5913  /system/lib/libhwui.so (android::uirenderer::skiapipeline::SkiaPipeline::renderFrameImpl(android::uirenderer::LayerUpdateQueue const&, SkRect const&, std::__1::vector<android::sp<android::uirenderer::RenderNode>, std::__1::allocator<android::sp<android::uirenderer::RenderNode>>> const&, bool, android::uirenderer::Rect const&, SkCanvas*, SkMatrix const&)+366)
  #50  pc 0x00000000002e3457  /system/lib/libhwui.so (android::uirenderer::skiapipeline::SkiaPipeline::renderFrame(android::uirenderer::LayerUpdateQueue const&, SkRect const&, std::__1::vector<android::sp<android::uirenderer::RenderNode>, std::__1::allocator<android::sp<android::uirenderer::RenderNode>>> const&, bool, android::uirenderer::Rect const&, sk_sp<SkSurface>, SkMatrix const&)+86)
  #51  pc 0x00000000002e31bb  /system/lib/libhwui.so (android::uirenderer::skiapipeline::SkiaOpenGLPipeline::draw(android::uirenderer::renderthread::Frame const&, SkRect const&, SkRect const&, android::uirenderer::LightGeometry const&, android::uirenderer::LayerUpdateQueue*, android::uirenderer::Rect const&, bool, android::uirenderer::LightInfo const&, std::__1::vector<android::sp<android::uirenderer::RenderNode>, std::__1::allocator<android::sp<android::uirenderer::RenderNode>>> const&, android::uirenderer::FrameInfoVisualizer*)+266)
  #52  pc 0x00000000003232b1  /system/lib/libhwui.so (android::uirenderer::renderthread::CanvasContext::draw()+576)
  #53  pc 0x00000000003227e1  /system/lib/libhwui.so (android::uirenderer::renderthread::DrawFrameTask::run()+156)
  #54  pc 0x000000000032f609  /system/lib/libhwui.so (android::uirenderer::WorkQueue::process()+164)
  #55  pc 0x000000000032f461  /system/lib/libhwui.so (android::uirenderer::renderthread::RenderThread::threadLoop()+72)
  #56  pc 0x000000000000d90b  /system/lib/libutils.so (android::Thread::_threadLoop(void*)+214)
  #57  pc 0x00000000000a7907  /apex/com.android.runtime/lib/bionic/libc.so (__pthread_start(void*)+20)
  #58  pc 0x00000000000611bf  /apex/com.android.runtime/lib/bionic/libc.so (__start_thread+30)`
