### ISSUE TITLE
NOT WORKING ON XIOAMI DEVICE 

### ISSUE THREAD

**Issue by Shaddynotshady** [googleads/googleads-mobile-flutter#712]
WORKING ON OTHER DEVICES BUT NOT OM XIAOMI DEVICES

**Comment by darshankawar** [comment]
@Shaddynotshady 
When opening an issue, please try to use [new issue template](https://github.com/googleads/googleads-mobile-flutter/issues/new?assignees=&labels=&template=2_bug.md&title=) and fill out requested details so that we can properly address the issue.
There's no details provided, so closing for now.
