### ISSUE TITLE
Warning Some apps have not been configured to use Apple's SKAdNetwork

### ISSUE THREAD

**Issue by mdmota** [googleads/googleads-mobile-flutter#731]
Some apps have not been configured to use Apple's SKAdNetwork.
To get credit for all ad-related activity, such as app installs, configure SKAdNetwork with recommended network IDs.

Do I need to configure this to receive payments or is there no need?

**Comment by huycozy** [comment]
Hi @mdmota 
What is your current ads plugin version? Please check this SO thread that may be useful: https://stackoverflow.com/questions/70626993/some-apps-havent-been-configured-to-use-apples-skadnetwork

**Comment by mdmota** [comment]
google_mobile_ads: ^2.3.0

**Comment by huycozy** [comment]
@mdmota Please try following the guideline from here: https://developers.google.com/admob/ios/quick-start#update_your_infoplist and re-check if the warning still persists or not.

**Comment by mdmota** [comment]
ok, but while I don't make this change, will I continue to receive payments normally?

**Comment by huycozy** [comment]
@mdmota `SKAdNetwork` is related to conversion tracking rather than distributing ads. So I don't think it will relate to your payment. Please see [this](https://developers.google.com/admob/ios/ios14#skadnetwork) for more information. 

Since this issue doesn't relate to ads plugin, I will close this from here. Once you've updated your app with addition SKAdNetwork but the warning still persists, feel free to write a comment and I will re-open this for further discussion. 

Thanks!
