### ISSUE TITLE
BANNER AD

### ISSUE THREAD

**Issue by greylabsofficial** [googleads/googleads-mobile-flutter#771]
when i update flutter to 3.7.3 adWidget start to give some errors for banner ad.
ERROR => 
AdWidget requires Ad.load to be called before AdWidget is inserted into the tree.
Parameter ad is not loaded. Call Ad.load before AdWidget is inserted into the tree.

i did not change any code. just update flutter version. and this error begin occurs.

**Comment by greylabsofficial** [comment]
pluginversion => 2.3.0 flutterversion =>3.7.3

**Comment by huycozy** [comment]
@greylabsofficial Please share the complete error log output so that we may verify the issue. 

Also, please provide a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example). You may also try with [google_mobile_ads example](https://github.com/googleads/googleads-mobile-flutter/tree/main/packages/google_mobile_ads/example).
