### ISSUE TITLE
android app not run so error

### ISSUE THREAD

**Issue by Mamunrex** [googleads/googleads-mobile-flutter#775]
googlemobileads/GoogleMobileAdsPlugin.java:416: error: incompatible types: Object cannot be converted to FlutterNativeTemplateStyle
                .setNativeTemplateStyle(call.argument("nativeTemplateStyle"))

**Comment by huycozy** [comment]
Please try running [plugin sample code](https://github.com/googleads/googleads-mobile-flutter/tree/main/packages/google_mobile_ads/example) and check if there is the same issue. You may compare your setup with the sample project to find the cause of this.

If the issue still occurs, please provide the complete output log so that we may verify the issue. And please provide the plugin version you are using as well. Thanks!
