### ISSUE TITLE
My program encountered an error

### ISSUE THREAD

**Issue by clondy999** [googleads/googleads-mobile-flutter#781]
My AndroidManifest.xml is
![image](https://user-images.githubusercontent.com/73311186/220920953-9e90ffc3-0628-4b7a-82ca-dc67bbe728b0.png)

![image](https://user-images.githubusercontent.com/73311186/220920552-4551fb1f-ca00-42c6-b49f-9c38de8fca06.png)

**Comment by huycozy** [comment]
@clondy999 
Please provide the information in text format instead of a screenshot for better readability. 
As I can see the issue from your screenshot, you are using the wrong app ID. You should follow up on the instruction there in the console log.

Also, this issue seems your question is best suited for support channels like StackOverflow, so please ask the same there for solutions if any.

Closing for now.
