### ISSUE TITLE
onPaidEvent not working for interstitial ads

### ISSUE THREAD

**Issue by Outthinkingpvt** [googleads/googleads-mobile-flutter#785]
Actually I am trying to use onPaidEvent to track the revenue value for native ads but the same callback( onPaidEvent) when I use for interstitial ads I don't get any suggestion to us it. Has anyone use it for interstitial ads?

**Comment by huycozy** [comment]
Please check this issue (https://github.com/googleads/googleads-mobile-flutter/issues/770) and try to provide information indicated in the issue template 

Hi 
When opening an issue, please try to provide all or some of the information indicated in the [template](https://github.com/googleads/googleads-mobile-flutter/issues/new?assignees=&labels=&template=2_bug.md&title=) so that we can address this issue properly.

<details>
<summary>Issue Template</summary>



## Plugin Version



## Steps to Reproduce



1. Run `flutter create bug`.
2. Update the files as follows: ... 
3. ... 

**Expected results:** 

**Actual results:** 

<details>
  <summary>Logs</summary>



```
```



```
```



```
```

</details>

</details>

Also, you may also take a look at https://github.com/googleads/googleads-mobile-flutter/issues/770#issuecomment-1429722366 which point out the cause of this issue in the production release.

**Comment by Outthinkingpvt** [comment]
I need to call onPaidEvent callback inside this piece of code but I am not able to call it here.


 _interstitialAd!.fullScreenContentCallback = FullScreenContentCallback(

      onAdShowedFullScreenContent: (InterstitialAd ad) =>
          print('ad onAdShowedFullScreenContent.'),
      onAdDismissedFullScreenContent: (InterstitialAd ad) {
        print('$ad onAdDismissedFullScreenContent.');
        ad.dispose();
        _createInterstitialAd();
      },

      onAdFailedToShowFullScreenContent: (InterstitialAd ad, AdError error) {
        print('$ad onAdFailedToShowFullScreenContent: $error');
        ad.dispose();
        _createInterstitialAd();
      },

// I am not getting option for onPaidEvent callback here
    

 
    );

**Comment by huycozy** [comment]
I checked with below snippet code and still see the `onPaidEvent` from the console log:

Sample code:
```
    _interstitialAd!.fullScreenContentCallback = FullScreenContentCallback(
      onAdShowedFullScreenContent: (InterstitialAd ad) {
        print('ad onAdShowedFullScreenContent.');

        ad.onPaidEvent = (ad, valueMicros, precision, currencyCode) {
          debugPrint(
              'onPaidEvent: $valueMicros - $precision - $currencyCode - ${ad.responseInfo!.adapterResponses!.length}');
          for (var response in ad.responseInfo!.adapterResponses!) {
            debugPrint(
                'Adapter response: ${response.adapterClassName} - ${response.adSourceName} - ${response.adSourceInstanceName} - ${response.description} ');
          }
        };
      },
      onAdDismissedFullScreenContent: (InterstitialAd ad) {
        print('$ad onAdDismissedFullScreenContent.');
        ad.dispose();
        _createInterstitialAd();
      },
      onAdFailedToShowFullScreenContent: (InterstitialAd ad, AdError error) {
        print('$ad onAdFailedToShowFullScreenContent: $error');
        ad.dispose();
        _createInterstitialAd();
      },
    );
```

Output log:
```
I/flutter (15450): onPaidEvent: 0.0 - PrecisionType.unknown - USD - 1
```

Can you try above snippet code or share your complete sample code as well?
