### ISSUE TITLE
Unhandled Exception: PlatformException(NativeAdError, Can't find NativeAdFactory with id: listTile, null, null)

### ISSUE THREAD

**Issue by Jasminsojitra** [googleads/googleads-mobile-flutter#789]
I got this error, I have try many solution but not resolved Unhandled Exception: PlatformException(NativeAdError, Can't find NativeAdFactory with id: listTile, null, null)

**Comment by huycozy** [comment]
Please try running [plugin's NativeAd sample code](https://github.com/googleads/googleads-mobile-flutter/blob/main/packages/google_mobile_ads/example/lib/reusable_inline_example.dart) and check if it works or not. 

If the issue still persists with this sample code, please provide the complete output of `flutter run -v` so that we may verify the issue. Thanks!
