### ISSUE TITLE
Native ads dont work when Google Playstore is disabled

### ISSUE THREAD

**Issue by ReggieMiller1** [googleads/googleads-mobile-flutter#790]
i noticed that Native ads do not work on debug mode while Playstore is disabled. i havent tested it using the release version while Playstore is disabled && if they were not to work while PlayStore is disabled it would be a disaster. what might be the cause of this issue?

**Comment by huycozy** [comment]
It seems your question is best suited for support channels like [google-admob-ads-sdk group](https://groups.google.com/g/google-admob-ads-sdk/), so please ask the same there for solutions if any.

If you are proposing a change, please use the appropriate new issue template and fill out the requested details so that we can address this issue properly.

Closing for now.
