### ISSUE TITLE
Error: MissingPluginException(No implementation found for method MobileAds#initialize on channel plugins.flutter.io/google_mobile_ads)

### ISSUE THREAD

**Issue by HarshilShiyani** [googleads/googleads-mobile-flutter#792]
Error: MissingPluginException(No implementation found for method MobileAds#initialize on channel plugins.flutter.io/google_mobile_ads)

**Comment by huycozy** [comment]
It looks like you are using this plugin on an environment other than Android or iOS, right? I ask this because there was an [old issue](https://github.com/googleads/googleads-mobile-flutter/issues/746) which had this error before (OP has run on Chrome whilst this plugin hasn't been supported on Web yet)
