### ISSUE TITLE
 Failed to Load A Banner AdNo ad config

### ISSUE THREAD

**Issue by theemperorharon** [googleads/googleads-mobile-flutter#809]
The error :  Failed to Load A Banner AdNo ad config
in google_mobile_ads: ^2.4.0
Flutter

**Comment by huycozy** [comment]
Hi @theemperorharon 
Please provide a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) so that we may verify this. Or you may use [plugin sample code](https://github.com/googleads/googleads-mobile-flutter/tree/main/packages/google_mobile_ads/example) to check if the issue still persists or not.
