### ISSUE TITLE
エラーが発生します

### ISSUE THREAD

**Issue by OOISHI-YASUO** [googleads/googleads-mobile-flutter#823]
Error: MissingPluginException(No implementation found for method _init on channel http://plugins.flutter.io/google_mobile_ads
)

```
    WidgetsFlutterBinding.ensureInitialized();
    MobileAds.instance.initialize();
```

**Comment by huycozy** [comment]
It looks like you are using this plugin on an environment other than Android or iOS, right? Because there was an https://github.com/googleads/googleads-mobile-flutter/issues/746 that had this error before (OP has run on Chrome whilst this plugin hasn't been supported on Web yet).

Closing this issue since there is little provided information. If you are proposing a change, please use the appropriate new issue template and fill out the requested details so that we can address this issue properly. Thanks!
