### ISSUE TITLE
`onAdDismissedFullScreenContent` is not called or is called after a few seconds when `InterstitialAd` closes

### ISSUE THREAD

**Issue by phamconganh** [googleads/googleads-mobile-flutter#824]
## Plugin Version
`google_mobile_ads: ^2.4.0`

## Steps to Reproduce

1. load `InterstitialAd` .
2. when loading is complete, set `ad.fullScreenContentCallback` and show.
3. `onAdDismissedFullScreenContent` navigate to new screen

**Expected results:** 
navigate to new screen with delay <= 0.3 milliseconds
**Actual results:** 
Sometimes `onAdDismissedFullScreenContent` is not called. Sometimes `onAdDismissedFullScreenContent` is delayed by a few seconds

**Comment by huycozy** [comment]
Hi @phamconganh 
Can you please provide a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) so that we may verify this?
You may also check [plugin sample code](https://github.com/googleads/googleads-mobile-flutter/tree/main/packages/google_mobile_ads/example) if it can help to elaborate the sample code or debug the issue.

**Comment by madx-47** [comment]
same issue happened with me.

**Comment by Jaew00Shin** [comment]
Same issues happened with me, too. Is there any update?

**Comment by SherwinDeveloper** [comment]
Having the same problem.
