### ISSUE TITLE
Google ads click wont give callback as the ads response

### ISSUE THREAD

**Issue by neeluagrawal04** [googleads/googleads-mobile-flutter#841]
Hi Team,
Google ads click gives the ad Manager callback which happens after the click navigation of screen, but i need the click and the data which is uploaded on payload before the navigation does.
So our google ads contains some of the deeplink when the user click on ads they will be navigated to browser first and then land to application again. The behaviour expected is to navigate directly to app deeplink instead of the browser.
Kindly check the issue once!!

**Comment by huycozy** [comment]
Hi @neeluagrawal04 
When opening an issue, please try to provide all or some of the information indicated in the [template](https://github.com/googleads/googleads-mobile-flutter/issues/new?assignees=&labels=&template=2_bug.md&title=) so that we can address this issue properly.

<details>
<summary>Issue Template</summary>



## Plugin Version



## Steps to Reproduce



1. Run `flutter create bug`.
2. Update the files as follows: ... 
3. ... 

**Expected results:** 

**Actual results:** 

<details>
  <summary>Logs</summary>



```
```



```
```



```
```

</details>

</details>

**Comment by neeluagrawal04** [comment]
Hi @huycozy 
Te google ads are showing using the ads manager but when i did clicked on any ads then it has the default behaviour to redirect to the web page and then navigates back to the deeplink which is added while creating ads.
And I need to redirect directly to app deeplink instead of web redirect and then to app again.

**Comment by huycozy** [comment]
@neeluagrawal04 The issue should be actionable with clear steps to reproduce it. Please try to provide all or some of the information indicated in the template I mentioned above. Thanks!
