### ISSUE TITLE
Dramatically decreased inter and rewarded show rate after update to 3.0.0

### ISSUE THREAD

**Issue by nechtas** [googleads/googleads-mobile-flutter#845]
## Plugin Version

3.0.0

## Steps to Reproduce

Doesn't have any additional info for now. We have several apps in both stores using google_mobile_ads. We recently updated the google_mobile_ads package to 3.0.0 from 2.3.0 and see a dramatically decreasing show rate for interstitials and rewarded videos. No of our code base changed, just the version bump of the package. There is a drop of more thane 5x in views and no fill rate spiked to 5x higher. This was also not clearly visible in the AdMob dashboard, just a revenue drop, we use Amplitude analytics so I found it there. 
Now we reverted the google_mobile_ads package to 2.3.0 and all metrics are back to normal, so it's clearly something changed in the last package version. Didn't find any braking changes or something that I should do in the docs. Any help or point on this topic would be appreciated.

**Comment by huycozy** [comment]
Hi @nechtas 
Thanks for the report. But I think this issue is related to many related factors (ads implementation, internet speed, ads server response time, etc), so it's not easy for us can investigate this issue properly. 

There is an existing [issue](https://github.com/googleads/googleads-mobile-flutter/issues/780) that presents a similar case about adaptive banner (he found the wrong implementation and also provide the fix at https://github.com/googleads/googleads-mobile-flutter/issues/780#issuecomment-1450376388). Please take a look at it and check if there is any useful information.

**Comment by nechtas** [comment]
Hi @huycozy
Thank you for your answer. I understand that this is a very frustrating issue because there is no other info, just my words. As I mentioned above there only change in our release was updating the package version to 3.0.0 and now we release a new app version with google_mobile_ads 2.3.0 and all our metrics are back to normal. No changes in the AdMob dashboard or our own code base. So for me, it's obvious, that it's related to the new package version. But I understand that if you had no fast answer to such a question it's almost impossible to figure out what's wrong. Maybe I missed some breaking changes between 2.x.x and 3.x.x?

**Comment by large** [comment]
@huycozy I can confirm that performance using 3.0.0 is really bad.
Running on Flutter (Channel stable, 3.10.1, on macOS 13.4 22F66 darwin-arm64, locale nb-NO) in a iOS emulator.
Internet speed is not an issue, look at these videos, with ads enabled:

https://github.com/googleads/googleads-mobile-flutter/assets/535446/bc788802-65ed-4324-b398-57799640d688

Ads disabled:

https://github.com/googleads/googleads-mobile-flutter/assets/535446/9c204b0e-4259-4d05-a1a1-e737ad960449

The only thing disabled between them is the ads...

**Comment by huycozy** [comment]
Hi @nechtas 
On which platform are you having an issue with your app (Android or iOS)? 

As far as I can see from the [changelog](https://pub.dev/packages/google_mobile_ads/changelog) from 2.4.0 to 3.0.0, there is one change that may be related to this issue: 

"_Fixes https://github.com/googleads/googleads-mobile-flutter/issues/700_" (if your flutter app is not add-to-app, this may be not related). 

I have temporarily ruled out the influence of the GMA dependency. However, if you have a native app using those versions, keep an eye on it to see if it encounters the same issue.

So far, we have not received similar reports. I would recommend you check the implementation of your ads again to see if there is any problem.

**Comment by huycozy** [comment]
@large Your issue looks like a performance issue than this issue. This issue is about `decreasing show rate for interstitials and rewarded videos`. Please file another issue for that and try to provide all information indicated in the issue template so that we may verify the issue properly. Thanks!

**Comment by huycozy** [comment]
>As we speak about our code base there only change in our release was upgrading this package and related ios mediation package versions.

Since there are no changes to this plugin related to mediation, it does not rule out the possibility that the new version of mediation you have upgraded is causing this issue. Can you try upgrading this plugin without upgrading mediation version? 

Since it may affect the production ads, I would recommend rolling out only a few users so it will not be affected if any.

Moreover, to be better (safer) for your metrics and revenue, please refer to this [thread](https://github.com/googleads/googleads-mobile-flutter/issues/780) on how to reproduce the issue with test ads and it will be actionable for us to verify this properly. Thank you!

**Comment by Jer0** [comment]
![image](https://github.com/googleads/googleads-mobile-flutter/assets/5064650/1646788d-0ce8-473f-91aa-fe9686064315)

I have the same problem @nechtas , I updated all my apps to the latest version of the package, I don't use mediation, everything comes from the admob network, the drop is significant, I updated them again and left the package with version 2.3.0

**Comment by cool2apps** [comment]
> ![image](https://user-images.githubusercontent.com/5064650/243201283-1646788d-0ce8-473f-91aa-fe9686064315.png)
> 
> I have the same problem @nechtas , I updated all my apps to the latest version of the package, I don't use mediation, everything comes from the admob network, the drop is significant, I updated them again and left the package with version 2.3.0

What about 2.4.0? Should we use 2.3.0 or 2.4.0 for higher eCPM? Thanks

**Comment by henghengzheng** [comment]
`AdError(code: 17, domain: com.google.admob, message: The provided view controller is not being presented.)`
This seems to be caused by these two issues, the same issue is found on iOS devices using 3.0.0 and 3.1.0.
I have cached ads in my program, and I will encounter the above problem when I need to display them for the second time.
I returned version 2.4.0.

**Comment by renis1235** [comment]
This is still open!
See https://github.com/googleads/googleads-mobile-flutter/issues/700
@henghengzheng has already pointed in the right direction.

**Comment by 10peter10** [comment]
I agree, I am still facing this issue,
I also commented at https://github.com/googleads/googleads-mobile-flutter/issues/700 .
Please let us know as soon as problem is solved.

**Comment by dominikhalvonik** [comment]
I agree, it is still open, as @10peter10  described
