### ISSUE TITLE
Admob Report show that App Open Ad request x10 times at some device.

### ISSUE THREAD

**Issue by HuyNguyen1590** [googleads/googleads-mobile-flutter#851]
## Plugin Version

2.0.1

## Explain
When i look at Admob report, open ad request a lot at sometimes that make show rate <5%. The rest of the day, everything is ok. I tried to **return** when App Open Ad showed once but it not fixed. Even set rate limit on Admob. I struggle with this bug over a month. Please help!!!

## Image
![Screenshot 2023-05-23 at 12 43 38](https://github.com/googleads/googleads-mobile-flutter/assets/63398750/fed3b311-6b1f-451d-ae38-1290297c58b6)

</details>

**Comment by huycozy** [comment]
Hi @HuyNguyen1590 
Since this issue is related to many related factors (ads implementation, internet speed, ads server response time, etc), it's not easy for us can investigate this issue properly.

If you encounter behavior that you believe could be a bug of ads plugin, please try to provide all information indicated in the template so that we may verify the issue properly.

Thank you!
