### ISSUE TITLE
google_mobile_ads package preventing flutter build ipa cmd from completing.

### ISSUE THREAD

**Issue by CrossfireGames09** [googleads/googleads-mobile-flutter#860]
Hi,
I recently updated Android Studio and flutter to the latest versions and went to build the latest update to my app. (this always built with no trouble before the update).
building the app bundle for android works fine but when i run the cmd flutter build ipa on mac, I get an error running pod install.

I then went back to an older version of the app that had only a couple of dependancies and ran the build cmd again and it worked. i then started adding the dependancies in again and would run the build cmd after adding each package.
after adding google_mobile_ads, the build cmd would return error running pod install.

**Comment by huycozy** [comment]
Hi @CrossfireGames09 
Please provide the complete output log of running build command with verbose (-v) so that we can verify the issue. 

You may want to refer to [writing and formatting syntax](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax) for beautifully formatted log output or save it as a file then attach the file here.
