### ISSUE TITLE
Why my google_mobile_ads has web_view ?

### ISSUE THREAD

**Issue by jtaxiexpress** [googleads/googleads-mobile-flutter#863]
<img width="576" alt="スクリーンショット 2023-06-14 0 54 34" src="https://github.com/googleads/googleads-mobile-flutter/assets/86914073/43df5e6b-75fb-4d16-b91b-4eda7b06d2ae">

## Plugin Version
google_mobile_ads: ^3.0.0

## Steps to Reproduce
flutter pub get

**Comment by huycozy** [comment]
Please check the changelog: https://pub.dev/packages/google_mobile_ads/changelog#300. For more details, it's added on PR https://github.com/googleads/googleads-mobile-flutter/pull/804 to implement WebView API feature (https://github.com/googleads/googleads-mobile-flutter/issues/618).

Closing this issue since it's not a plugin bug or feature request.
