### ISSUE TITLE
RewardedAd LoadAdError code: 3

### ISSUE THREAD

**Issue by vienhp1996** [googleads/googleads-mobile-flutter#909]
the code works fine with the test id, but when I change my id, it doesn't load on android. I don't understand what the No fill response means
  
  `LoadAdError(code: 3, domain: com.google.android.gms.ads, message: No fill., responseInfo: ResponseInfo(responseId: null, mediationAdapterClassName: , adapterResponses: [], loadedAdapterResponseInfo: null), responseExtras: {})`
  
  
 _createRewardedAd() async {
    // Platform.isAndroid ? 'ca-app-pub-3940256099942544/5224354917' : 'ca-app-pub-3940256099942544/1712485313'
    RewardedAd.load(
        adUnitId: Platform.isAndroid ? ANDROID_ADS_ID : IOS_ADS_ID,
        request: const AdRequest(),
        rewardedAdLoadCallback: RewardedAdLoadCallback(
          // Called when an ad is successfully received.
          onAdLoaded: (ad) {
            // debugPrint('$ad loaded.');
            // Keep a reference to the ad so you can show it later.
            _rewardedAd = ad;
          },
          // Called when an ad request failed.
          onAdFailedToLoad: (LoadAdError error) {
            debugPrint('RewardedAd failed to load: $error');
            _rewardedAd = null;
            _numRewardedLoadAttempts += 1;
            if (_numRewardedLoadAttempts < maxFailedLoadAttempts) {
              _createRewardedAd();
            }
          },
        ));
  }

`   • Flutter version 3.10.5 
    • Dart version 3.0.5
    • DevTools version 2.23.1
`

**Comment by huycozy** [comment]
Hi @vienhp1996 
It seems your issue is best suited on [Developer Forum](https://groups.google.com/forum/#!categories/google-admob-ads-sdk). I can see there are some similar issue there with above error code and message:

- https://groups.google.com/g/google-admob-ads-sdk/c/1Q9rRNVAKYo/m/XBhQseM2AQAJ
- https://groups.google.com/g/google-admob-ads-sdk/c/iyh17o76g44/m/UozyrWyHAAAJ

That being said, this googleads-mobile-flutter plugin and ads SDK in general don't have control on ad request fill rate. So I will close this issue as it's not a plugin issue. Thanks!
