### ISSUE TITLE
How to change NativeAds ad layout using flutter only

### ISSUE THREAD

**Issue by winterdl** [googleads/googleads-mobile-flutter#914]
We could change NativeAds style by nativeTemplateStyle: NativeTemplateStyle, but how could we change the layout of an ad using flutter code only?

**Comment by huycozy** [comment]
Hi @winterdl 
Currently, there are two layout types from the supported template: medium and small. And you can pass your preferred type via NativeTemplateStyle's `templateType`. 

Your question is best suited for support channels like StackOverflow, so please ask there for further questions. If you are proposing a change, please use the appropriate new issue template and fill out the requested details so that we can address this issue properly.

Closing from here as this is more of a `how-to` question rather than a bug or feature request.
