### ISSUE TITLE
[Feature request] Add methods from UMP 2.1.0

### ISSUE THREAD

**Issue by Reprevise** [googleads/googleads-mobile-flutter#944]
UMP 2.1.0 released months ago, and came with some quality of life improvements for developers. It would be nice to see these methods implemented in the Dart wrapper.

**Comment by huycozy** [comment]
Hi @Reprevise 
UMP 2.1.0 dependency has been added since [3.1.0](https://pub.dev/packages/google_mobile_ads/changelog#310) release. Could you be more specific on which methods should be implemented?

**Comment by Reprevise** [comment]
Some convenience methods have been added, here are the release notes for [Android](https://developers.google.com/admob/android/privacy/release-notes) (same on iOS).

**Comment by malandr2** [comment]
@Reprevise Ack. Thanks, this is on our radar to be implemented in 2024; however nothing has been officially decided as of yet.

**Comment by absar** [comment]
Since the other specific request #1003 for consent methods is closed in favor of this ticket, copying here for future reference: 

These methods and getters to give an option to the user to update consent are missing in Flutter implementation whereas these are available in both Android and iOS since July-2023
`ConsentInformation.privacyOptionsRequirementStatus`
`UserMessagingPlatform.showPrivacyOptionsForm`

While there is `ConsentInformation.reset` as per the docs it should only be used for testing purposes to simulate a user's first install experience or to remove UMP SDK completely

**Comment by Phlphat746** [comment]
I don't think it's appropriate to change the device. It's better to use the old device because it will reduce the extravagance of the team that has to use technology that may not be better. I don't think so because Flutter is just a new idea.  Haven't done anything yet.  Or there may be (funds) as well.  Arranged (group scholarship 555?

**Comment by skiluk** [comment]
Yes please add the convenience methods from previous release to the Dart wrapper version. We specifically need canRequestAds()

https://developers.google.com/admob/android/privacy/release-notes

**Comment by malandr2** [comment]
Closing as https://github.com/googleads/googleads-mobile-flutter/pull/1062 has resolved this. These APIs will be included in our next release.
