### ISSUE TITLE
Ads not show and raise exception "No ad to show", but native Swift is showing correctly

### ISSUE THREAD

**Issue by dphans** [googleads/googleads-mobile-flutter#996]
## Plugin Version

```
# pubspec.yaml
dependencies:
  flutter:
    sdk: flutter
  google_mobile_ads: ^4.0.0
```

## Steps to Reproduce

1. Add `google_mobile_ads: ^4.0.0` into `pubspec.yaml`.
2. Register app id into `Info.plist` (following `GADApplicationIdentifier`).
3. Initialize plugin in `main.dart` after `WidgetsFlutterBinding.ensureInitialized();`: `await MobileAds.instance.initialize();`.
4. Request ATT on iOS 14 with `await AppTrackingTransparency.requestTrackingAuthorization();` (by plugin `app_tracking_transparency: ^2.0.4`).
5. Create and load `BannerAd` with correct ad type, size and unit id.
6. Wrap ad into `ConstrainedBox` to keep ad size is valid with AdMob policy with type **Banner** (min width, min height should be larger or qual to 320x50).

**Expected results:** Ad display correctly.

**Actual results:** Ad not show and callback return error "Request Error: No ad to show.".

## Other description

1. I try to replace ad unit id into test unit ids provide by official documentations (which defined in [https://developers.google.com/admob/android/test-ads#demo_ad_units](https://developers.google.com/admob/android/test-ads#demo_ad_units)) and it display correctly.
2. I try to create new empty Swift project (native Swift 5 with Storyboard) and it work correctly with my ad unit id.

**Comment by malandr2** [comment]
Hi @dphans, given the google_mobile_ads plugin is able to display the test ads correctly, this appears to be an ad serving rather than directly related to the Flutter plugin. 

As an actionable next step, please create a new thread in the [AdMob Developers Forum](https://groups.google.com/g/google-admob-ads-sdk), you can link to this GitHub if you choose, and please include your App ID and ad unit ids so your issue can be appropriately triaged. Closing this issue out. Thanks!
